version: '3'
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  ruby_redis:
    image: redis:4.0-alpine
    command: redis-server
    networks:
      - development
    volumes:
      - shared_data:/var/shared/redis
  ruby_db:
    image: postgres:12.5-alpine
    container_name: ruby_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5099:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: entrypoint.sh
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - ruby_db