default: &default
  adapter: postgresql
  encoding: unicode
  host: ruby_db
  username: postgres
  password: password
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_db
